apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-platform-suite-component-yzml
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-platform-suite-component-yzml
    app.kubernetes.io/part-of: multi-platform-suite-application-jhsz
  name: multi-platform-suite-component-yzml
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: multi-platform-suite-component-yzml
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: multi-platform-suite-component-yzml
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-platform-i-2-tenant/multi-platform-suite-application-jhsz/multi-platform-suite-component-yzml@sha256:a169fc09dd642d7dd6df5eb345958579bbdc1650e421905c788a88499ceb1274
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
